# Default config for Akela
baseUrl: http://127.0.0.1:4173
headless: true
reportDir: reports
plansDir: plans
journeysDir: journeys
snowplow:
  collectorPatterns:
    - "/i"
    - "/com.snowplowanalytics.snowplow/tp2"
    - "/snowplow/"
